[project]
name = "fast-api-jaffle-shop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "duckdb>=1.2.1",
    "fastapi[standard]>=0.115.12",
    "pytest>=8.3.5",
    "ruff>=0.11.2",
]
