
name: lint

on:
  push:
    branches:
      - main
      - devel
  pull_request:
    branches:
      - main
      - devel
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  lint:
    name: lint
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
        python-version: ["3.11.x"]

    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}

    steps:

      - name: Check out
        uses: actions/checkout@master
        with:
          submodules: 'true'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: yezz123/setup-uv@v4
        with:
          uv-venv: ".venv"

      - name: Install dependencies
        run: make dev

      - name: Run make lint
        run: make lint

